### ISSUE TITLE
Upgraded to FF87 Dev Edition. All the XUL addons from here got disabled. Now what?

### ISSUE THREAD

**Issue by mzso** [xiaoxiaoflood/firefox-scripts#74] opened 2021-03-25 16:31 UTC
As well, as some others. What gives? 
It worked initially, but while running FF decided to permanently disable them on the fly. How do I fix this?
(The message was something about them cannot be verified, but localized to my language.)

I even tried upgrading to the latest config.js, which I didn't do the last update. (yet everything worked.) As well as the files in chrome/utils. It didn't help.
Do extensions that were disabled like this remain disabled, or something is still wrong?

**Comment by mzso** [comment] 2021-03-25 16:35
Well, apparently I can't restart any either, because the browser claims its corrupted.

**Comment by xiaoxiaoflood** [comment] 2021-03-26 03:29
As they are legacy addons, they don't delete settings on uninstall, so you probably can uninstall them, restart Fx then reinstall.

But make a backup of your profile folder first.

**Comment by mzso** [comment] 2021-03-26 09:29
[**@xiaoxiaoflood**](https://github.com/xiaoxiaoflood) commented on [2021. márc. 26. 04:29 CET](https://github.com/xiaoxiaoflood/firefox-scripts/issues/74#issuecomment-807909841 "2021-03-26T03:29:28Z - Replied by Github Reply Comments"):
> Legacy addons almost never delete settings on uninstall, so you probably can uninstall them, restart Fx then reinstall.
> 
> But make a backup of your profile folder first.

I see. Well, I managed to do it. Though for one of them I don't have the xpi.
Do you know where the permanently disabled state is stored?

**Comment by xiaoxiaoflood** [comment] 2021-03-26 13:09
> Do you know where the permanently disabled state is stored?

`extensions.json` in profile folder. If the toggle switch is not available in `about:addons`, you are probably looking for `"appDisabled":true` in each disabled legacy addon. With Fx closed, change it to `false`, then the toggle switch will reappear if you have fixed what caused the issue.

**Comment by mzso** [comment] 2021-03-26 13:48
[**@xiaoxiaoflood**](https://github.com/xiaoxiaoflood) commented on [2021. márc. 26. 14:09 CET](https://github.com/xiaoxiaoflood/firefox-scripts/issues/74#issuecomment-808202716 "2021-03-26T13:09:54Z - Replied by Github Reply Comments"):
> > Do you know where the permanently disabled state is stored?
> 
> `extensions.json` in profile folder. If the toggle switch is not available in `about:addons`, you are probably looking for `"appDisabled":true` in each disabled legacy addon. With Fx closed, change it to `false`, then the toggle switch will reappear if you have fixed what caused the issue.

Thanks!

**Comment by xiaoxiaoflood** [comment] 2021-03-29 02:38
Closing this one because I guess your problem wasn't a bug caused by scripts/extensions in this repo. If you think otherwise and know the steps to reproduce the issue, please post it here and I'll reopen this.

**Closed by xiaoxiaoflood** 2021-03-29 02:38 UTC
