### ISSUE TITLE
rebuild_userChrome.uc.js

### ISSUE THREAD

**Issue by Orriky** [xiaoxiaoflood/firefox-scripts#35] opened 2020-05-23 06:56 UTC
Hi,

right click to edit the script does not work

**Comment by xiaoxiaoflood** [comment] 2020-05-23 16:35
That's because Fx doesn't have a default editor anymore (Scratchpad). You need to set the path of your editor in `about:config`'s `view_source.editor.path`. Something like `C:\WINDOWS\system32\notepad.exe` if you're on Windows. I use Notepad++.

**Comment by xiaoxiaoflood** [comment] 2020-05-23 16:40
Duplicate of #23.

**Closed** 2020-05-24 18:23 UTC
Labels: duplicate
