### ISSUE TITLE
Keyconfig doesn't seem to be fully working. 

### ISSUE THREAD

**Issue by mzso** [xiaoxiaoflood/firefox-scripts#58] opened 2020-11-14 15:41 UTC
Hi!
I had Dorando keyconfig for a long while.
I copied all `extensions.dorandoKeyConfig.*` settings to prefs.js. But almost neither seem to show up or function. The one that works is the hotkey to open the keyconfig settings window. Which is fortunate, because I have no idea how to open it otherwise. How do you do that in current FF?
I checked, the settings are still there in prefs.js, so firefox didn't remove them. So I have no idea why it doesn't work.

Also, the text coloring doesn't work. normally user created shortcuts are purple. But now this single hotkey that works is just plain black. The other colors seem to work. Red for disabled.  And blue/orange I forgot what for.

**Comment by xiaoxiaoflood** [comment] 2020-11-15 21:37
> How do you do that in current FF?

![image](https://user-images.githubusercontent.com/25161346/99197393-0397cd80-2771-11eb-9587-13a60a89ee5b.png)
or
![image](https://user-images.githubusercontent.com/25161346/99197402-16120700-2771-11eb-818d-0c12589ba147.png)


> Also, the text coloring doesn't work. normally user created shortcuts are purple. But now this single hotkey that works is just plain black.

Everything is fine here.
![image](https://user-images.githubusercontent.com/25161346/99197458-67ba9180-2771-11eb-9c4b-3344d65545c9.png)

So I can't reproduce the issue without further details. Keyconfig is fully working for me on Fx 83.0b10.

**Comment by mzso** [comment] 2020-11-16 00:11
@xiaoxiaoflood 
Newly created keys seem to have proper color. Old ones don't, apparently. Don't know why. Just plain copied settings as I said. From the old prefs.js, to the new one. Then installed the extension.

Yeah, I didn't find the settings at first. (By default there's no options button, only a hidden menu item in the addon manager. )

**Comment by xiaoxiaoflood** [comment] 2020-11-17 00:19
So I:

1. Created a new profile.

2. Installed userChromeJS (copying files).

3. With Fx closed, copy all and only `extensions.dorandoKeyConfig.*` prefs from my default profile to new one's prefs.js.

4. Opened Fx with the new profile and installed keyconfig.

I didn't even have to restart again (because keyconfig wasn't built to be restartless, it isn't a true bootstrapped addon). Keyconfig is fully working. My personal hotkeys are working and showing up with proper colors in keyconfig manager.

It may be obvious, but you should only change prefs.js when you're sure Fx is not running with your profile. Opened profile rewrites prefs.js all the time, so it's useless to edit the file while Fx is open.

**Comment by mzso** [comment] 2020-11-17 01:30
@xiaoxiaoflood Well, all I can do is scratch my head, because I pretty much did the same

**Comment by xiaoxiaoflood** [comment] 2020-11-17 03:51
Maybe can you paste your `extensions.dorandoKeyConfig.*` for me to test if there is something special with them? Or are they too personal?

**Comment by mzso** [comment] 2020-11-17 09:35
[**@xiaoxiaoflood**](https://github.com/xiaoxiaoflood) commented on [2020. nov. 17. 04:51 CET](https://github.com/xiaoxiaoflood/firefox-scripts/issues/58#issuecomment-728669189 "2020-11-17T03:51:59Z - Replied by Github Reply Comments"):
> Maybe can you paste your `extensions.dorandoKeyConfig.*` for me to test if there is something special with them? Or are they too personal?

Not really, it's just filled with embarassing tinkered disabled a non-working stuff. :)

I did it again, this time it appeared in the new profile. Maybe something went wrong with copy pasting. Or maybe I installed keyconfig first and there were some duplicate items.

Unfortunately most don't work though. Perhaps (if it's not too much to ask) you could tell me how to load an url in a tab, that would be good to open extension settings, especially nowadays with webextensions if I can figure out their urls.
Also my hotkeys for DTA mostly work except for saving hovered links with DTA, which was really useful. (Influenced by old flashgot addon which got abandoned before XUL addons)

Don't know, maybe this is too complicated:
```JS
    /*Code*/
    // Save Link with dTa! OneClick
    Components.utils.import("resource://gre/modules/ctypes.jsm");
    var user32 = ctypes.open("user32");
    var BOOL = ctypes.int;
    var LONG = ctypes.long;
    var POINT = ctypes.StructType("tagPOINT", [{x:LONG}, {y:LONG}]);
    var LPPOINT = POINT.ptr;
    var GetCursorPos = user32.declare('GetCursorPos', ctypes.winapi_abi, BOOL, LPPOINT);
    var point = new POINT;
    if (GetCursorPos(point.address())) {
      var utils = window.QueryInterface(Components.interfaces.nsIInterfaceRequestor).
        getInterface(Components.interfaces.nsIDOMWindowUtils);
      var MOUSEEVENTF_RIGHTDOWN = 0x0008;
      var MOUSEEVENTF_RIGHTUP = 0x0010;
      utils.sendNativeMouseEvent(point.x, point.y, MOUSEEVENTF_RIGHTDOWN | MOUSEEVENTF_RIGHTUP, 0, null);
    }
    user32.close();
    setTimeout(function () {
      document.getElementById("dta:turbo-link").doCommand();
      document.getElementById("contentAreaContextMenu").hidePopup();
      setTimeout(function () {
        var win = Services.wm.getMostRecentWindow("alert:alert");
        if (win &&
            win.document.getElementById("alertTitleLabel") &&
            win.document.getElementById("alertTitleLabel").value == "DownThemAll!") {
          win.onAlertClose();
        }
      }, 2000);
    }, 1000);
```




[Clipboarder.2020.11.17.txt](https://github.com/xiaoxiaoflood/firefox-scripts/files/5552386/Clipboarder.2020.11.17.txt)

**Comment by xiaoxiaoflood** [comment] 2020-11-18 03:46
Ah. Your hotkeys are like

> user_pref("extensions.dorandoKeyConfig.main.xxx_key1_Gyorskeresés 2.", "!][][][gFindBar.startFind(gFindBar.FIND_TYPEAHEAD);][chrome://browser/content/browser.xul");

Since Fx 69 the main window URL changed from `chrome://browser/content/browser.xul` to `chrome://browser/content/browser.xhtml`.

If you're trying to use so outdated codes, probably some (or many) of them won't work. There's a reason why I had to fix so many things in every single addon on this repo to get them to work in current Fx.

Sorry, but I cant fix things for you.

About the code you pasted, I quickly noticed that
`var utils = ...`
is outdated, you should use `windowUtils.sendNativeMouseEvent` directly instead of `utils.sendNativeMouseEvent`.

That's all I can do, sorry.

**Comment by mzso** [comment] 2020-11-18 10:32
@xiaoxiaoflood 
Thanks for the tips.

**Comment by xiaoxiaoflood** [comment] 2020-11-24 03:55
Closing this one as apparently it's not keyconfig's bug but the use of outdated codes as hotkeys.

**Closed by xiaoxiaoflood** 2020-11-24 03:55 UTC
