### ISSUE TITLE
Sometimes context menu items are added multiple times

### ISSUE THREAD

**Issue by mzso** [xiaoxiaoflood/firefox-scripts#111] opened 2021-12-27 20:02 UTC
Hi!

I have a script that uses the context menu items, so I almost reported a download being added multiple times issue.
But it turns out that there are multiple context menu items for the same thing. Not sure how permanent it will be. I did an update today to the latest version you mentioned in the other issue, that may be a factor.
This is here on github:
Empty page area:
![kép](https://user-images.githubusercontent.com/4479090/147503402-7f9b49b6-b084-4f2f-b446-a8ca1fcac3ae.png)
Link:
![kép](https://user-images.githubusercontent.com/4479090/147503467-13108acc-eabb-49d1-a8d6-395744743f72.png)
image/link:
![kép](https://user-images.githubusercontent.com/4479090/147503498-18798e8b-1b99-4230-a954-657a5288889b.png)

**Comment by xiaoxiaoflood** [comment] 2021-12-27 22:29
Can't reproduce. Even after updating the extension, there are no duplicates.

It looks like you use scripts or legacy extensions from other sources ("*Send to Urlbar*" is not native) and there may be incompatibilities.

Unless someone provides steps to reproduce involving only Fx native features plus scripts/extensions from my page, there's not much I can do.

**Comment by mzso** [comment] 2021-12-28 10:25
@xiaoxiaoflood 
No worries. It happened twice in a month or so, maybe due to upgrading. Not a huge issue.

**Comment by xiaoxiaoflood** [comment] 2022-08-01 21:24
Closing this one for inability to reproduce. If it happens to you again and you can find the steps for that, please let me know.

**Closed by xiaoxiaoflood** 2022-08-01 21:24 UTC
