### ISSUE TITLE
Libreoffice downloads failing

### ISSUE THREAD

**Issue by mzso** [xiaoxiaoflood/firefox-scripts#78] opened 2021-04-17 12:05 UTC
Hi!

I tried to download Libreoffice files, from the official source:
https://www.libreoffice.org/download/portable-versions/
https://www.libreoffice.org/download/download/

The downloads started allright, but when they reached 100% I got a file access error of sorts:
![kép](https://user-images.githubusercontent.com/4479090/115112349-6fcb6700-9f85-11eb-916c-2036fcbad97c.png)

I tried downloading from elsewhere which completed successfully, so it's unlikely to be a local issue.
Maybe it's related to that metalink feature, which I only ever saw with libreoffice downloads.

**Comment by xiaoxiaoflood** [comment] 2021-04-23 01:56
I couldn't reproduce the issue. Right-clicked `LibreOffice 7.1.2 Portable MultilingualStandard`, then `Save Link with dTa! One Click`. Download started and ended flawlessly. Developer Edition 88.9b9, latest DTA!.

**Comment by mzso** [comment] 2021-04-25 21:50
[**@xiaoxiaoflood**](https://github.com/xiaoxiaoflood) commented on [2021. ápr. 23. 03:56 CEST](https://github.com/xiaoxiaoflood/firefox-scripts/issues/78#issuecomment-825327603 "2021-04-23T01:56:16Z - Replied by Github Reply Comments"):
> I couldn't reproduce the issue. Right-clicked `LibreOffice 7.1.2 Portable MultilingualStandard`, then `Save Link with dTa! One Click`. Download started and ended flawlessly. Developer Edition 88.9b9, latest DTA!.

Well, I can only scratch my head. I still get the file access error when the download is supposed to be finishing.

**Comment by xiaoxiaoflood** [comment] 2021-05-05 03:07
I managed to reproduce the issue. It was really a bug. This should be fixed now.

**Closed** 2021-05-05 03:06 UTC

**Comment by mzso** [comment] 2021-05-05 11:54
@xiaoxiaoflood 
Great! Thanks!

**Comment by mzso** [comment] 2021-05-08 13:35
[**@xiaoxiaoflood**](https://github.com/xiaoxiaoflood) commented on [2021. máj. 5. 05:07 CEST](https://github.com/xiaoxiaoflood/firefox-scripts/issues/78#issuecomment-832384165 "2021-05-05T03:07:23Z - Replied by Github Reply Comments"):
> I managed to reproduce the issue. It was really a bug. This should be fixed now.

Okay. So now trying to try it I ran into issues.
First I tried plain in-browser updates. I updated twice, but I'm still on the 2021.03.25 version. (Unfortunately I didn't pay attention to the version number before)

So then I tried from here, but I get a corrupted addon message and it won't get installed. Something's wrong.

**Comment by xiaoxiaoflood** [comment] 2021-05-08 17:11
This is expected, recently I updated userChromeJS in 5403e13336eff759162c115f37c50ecde32d3e25 for #79, so you need to manually update your chrome/utils folder.

**Comment by mzso** [comment] 2021-05-08 18:08
[**@xiaoxiaoflood**](https://github.com/xiaoxiaoflood) commented on [2021. máj. 8. 19:11 CEST](https://github.com/xiaoxiaoflood/firefox-scripts/issues/78#issuecomment-835433070 "2021-05-08T17:11:44Z - Replied by Github Reply Comments"):
> This is expected, recently I updated the _legacy extensions loader_ in [5403e13](https://github.com/xiaoxiaoflood/firefox-scripts/commit/5403e13336eff759162c115f37c50ecde32d3e25) for [#79](https://github.com/xiaoxiaoflood/firefox-scripts/issues/79), so you need to manually update your chrome/utils folder. And don't forget to restart Fx forcing to clear startup-cache to force the browser to use the updated code.

I see, but will it work with the FF version that I'm on? (87)
And will the older versions of addons from here work?

**Comment by xiaoxiaoflood** [comment] 2021-05-08 18:12
Yes for both.
