### ISSUE TITLE
Firefox 101

### ISSUE THREAD

**Issue by lanx73** [xiaoxiaoflood/firefox-scripts#142] opened 2022-05-31 12:09 UTC
Hi, just updated Firefox to version 101 and it looks like userChromeJS scripts are no longer working. 😱😭

**Comment by xiaoxiaoflood** [comment] 2022-05-31 13:53
I've been using v101 for like a month. It's working. Be sure you have the updated files.

**Comment by mozo78** [comment] 2022-06-01 16:01
Same here. I'm with the latest version of the files. Before I update them, if I downgrade to a lower FF version, there's been status bar. Now, with the new files, I dont have status bar with older and the newest FF versions. I beg for some help.

**Comment by 1031982** [comment] 2022-06-02 14:59
I have just installed the updated files, and the script for the status bar is not working.

**Comment by xiaoxiaoflood** [comment] 2022-06-02 16:22
Contents of **utils.zip**, **utils_extensions_only.zip**, **utils_scripts_only.zip** and **chrome/utils** are exactly the same, of course within the limits of each one (for instance, **utils_scripts_only.zip** doesn't have **BootstrapLoader.jsm**).

The same applies to **fx-folder.zip** and **installation-folder** (the difference here is that the zip already creates the folder structure).

There's nothing outdated or link to an older version. Links in readme don't point to specific commit but to current versions.

Example of permalink:
https://github.com/xiaoxiaoflood/firefox-scripts/raw/8764048e0397ba9db174344813d674c104805560/utils.zip

Example of "always current" link (used in readme):
https://raw.githubusercontent.com/xiaoxiaoflood/firefox-scripts/master/utils.zip

**Comment by xiaoxiaoflood** [comment] 2022-06-02 16:35
I believe the issue reported here is a dupe of this one: #127

As you can see, that was fixed in April. Those reporting issues in v101 are probably just using an outdated version of userChromeJS. One way to notice that is if you still have the file **boot.jsm** in **/chrome/utils**. This file no longer exists.

After *reinstalling* userChromeJS basic files, be sure to clear startup cache (step 6 in readme Instructions).

**Comment by 1031982** [comment] 2022-06-02 18:09
> You have to download firefox-scripts-master.zip. The link in the tutorial leads to an older version of the files. Today I tried it on Linux Mint and it's working fine.

Well, I can't seem to find that file, so I can't exactly us it.

**Comment by mozo78** [comment] 2022-06-02 18:14
Here it isL
![Screenshot_20220602_211222](https://user-images.githubusercontent.com/38666396/171698396-6cfda1db-b4e0-4675-ac46-0f61dfb6a821.png)

**Comment by koijigen** [comment] 2022-06-02 19:42
> I tried the files from the tutorial and it doesn't work. When I downloaded master, it worked. I don't know why it was like that. Anyway, everything is fine, thank you :)

worked. thank you!

**Comment by mozo78** [comment] 2022-06-02 20:25
> That file made no difference, still no status bar at the bottom.

Where you put status-bar.uc.js?

**Comment by 1031982** [comment] 2022-06-02 21:23
> > That file made no difference, still no status bar at the bottom.
> 
> Where do you put status-bar.uc.js?

The chrome folder that's inside my profile folder. 
C:\Users\-Windows account name-\AppData\Roaming\Mozilla\Firefox\Profiles\-profile id-\chrome

**Comment by 1031982** [comment] 2022-06-03 02:26
For further information, I have now created a new profile, downloaded everything again, followed the instructions, and it still does not work for me.

**Comment by Reibies** [comment] 2022-06-07 05:32
I, too, am having no luck loading some scripts, but I'm mostly concerned with StyloaiX not working despite downloading the update for 101.

**Comment by yangchuansheng** [comment] 2022-06-09 14:00
How to resolve this issue？

![](https://pek3b.qingstor.com/kubesphere-community/images/202206092200643.png)

**Comment by xiaoxiaoflood** [comment] 2022-06-09 14:09
> How to resolve this issue？

Just like I said in a [comment above](https://github.com/xiaoxiaoflood/firefox-scripts/issues/142#issuecomment-1145073443) this StyloaiX issue was also introduced by Fx 101 and was fixed in April: #130.

userChromeJS things don't have autoupdate, neither scripts nor the *base files*. When something breaks, the first thing to do is to assure you're using the most recent versions (userChromeJS + scripts).

**Comment by 1031982** [comment] 2022-06-30 07:14
Update : 
I have no idea what changed with Firefox 102, but I got the status-bar working again.

**Closed** 2022-08-01 21:27 UTC
