### ISSUE TITLE
Mouse Gestures Scroll To Top

### ISSUE THREAD

**Issue by zakius** [xiaoxiaoflood/firefox-scripts#36] opened 2020-06-12 21:32 UTC
Hello, first of all I'd like to thank you for sharing your work. As I can see you have scroll to top action bound in gestures script but I can't get it to work any way, most likely it should replicate scroll to bottom (sending keystroke), but I can't figure out what would be the code for `Home` button (obviously changing `23` to `24` in that number doesn't work). Do you have any reference how to find these codes?

**Comment by xiaoxiaoflood** [comment] 2020-06-13 00:50
Hi,

Maybe you're using an outdated code? Mouse Gestures uses [cmd_moveBottom](https://github.com/xiaoxiaoflood/firefox-scripts/blob/master/chrome/mouseGestures.uc.js#L48) and [cmd_moveTop](https://github.com/xiaoxiaoflood/firefox-scripts/blob/master/chrome/mouseGestures.uc.js#L178).

> Do you have any reference how to find these codes?

https://searchfox.org/mozilla-central/source/testing/mochitest/tests/SimpleTest/NativeKeyCodes.js

**Comment by zakius** [comment] 2020-06-13 08:22
Thanks for the quick reply

These commands don't work for me for some reason, maybe there's some version mismatch or other issue, I'll look into it one more time. And thank you for that list

**Comment by ganego** [comment] 2020-06-13 09:30
I use a different script that calls one of these function: https://developer.mozilla.org/en-US/docs/Archive/Mozilla/XUL/List_of_commands

Specifically `cmd_scrollTop`. Don't know if this is possible here.

**Comment by zakius** [comment] 2020-06-13 20:33
Just letting you know I figured it out

first of all this command works but has to be called in the right context, directly in the mousedown handler

secondly I had some issues with making rocker left work properly which may have caused false negatives, in particular deselect command was messing with it, for my usecase it doesn't really matter so I just commented it out and now it does what I expect


thanks again

**Comment by xiaoxiaoflood** [comment] 2020-06-13 21:30
> first of all this command works but has to be called in the right context, directly in the mousedown handler

Which command? I use `cmd_moveBottom` and `cmd_moveTop` in mouseup handler, like all mouse gestures. Rocker gestures are handled by mousedown and scroll gestures by wheel.


> I use a different script that calls one of these function (...) Specifically `cmd_scrollTop`

Do you have an example where scrollTop/scrollBottom work and moveBottom/moveTop don't?
I think they and cmd_[begin|end]Line are essentially the same.

[Windows](https://searchfox.org/mozilla-central/source/dom/events/win/ShortcutKeyDefinitions.cpp#85-86) and [Linux](https://searchfox.org/mozilla-central/source/dom/events/unix/ShortcutKeyDefinitions.cpp#39-40) uses cmd_[begin|end]Line for Home/End keys in browser context, while [Mac](https://searchfox.org/mozilla-central/source/dom/events/mac/ShortcutKeyDefinitions.cpp#34-35) uses cmd_scroll[Top|Bottom].

**Comment by zakius** [comment] 2020-06-13 21:39
I'm not sure if I use `move` or `scroll`, will check tomorrow, but what I meant it doesn't work in `chromeListener` at all, so I gave up on sending message from mousedown handler and executed these commands directly there

**Comment by xiaoxiaoflood** [comment] 2020-06-13 23:41
So I got two examples where gesture to scrollup/down doesn't work:

- Searchfox, at least before you leftclick the scrollabe element to give it focus:
https://searchfox.org/

- CodeMirror:
https://codemirror.net/demo/simplemode.html
(example of site using CodeMirror: codepen.io)

I already fixed that and will push the update soon. We'll back to simulating key inputs, that's the only way I got to solve it.

**Comment by zakius** [comment] 2020-06-14 12:06
Do you mind if I submit PR with improved configurability? I'd build array of available actions and map gestures to them somewhere at the top of the script to make it clearer and easier to update for people who customized their bindings

**Comment by xiaoxiaoflood** [comment] 2020-06-14 20:18
Go ahead! But yes, I think it's not so easy at it may seen. I didn't actually write the script to make it easily configurable.

**Comment by xiaoxiaoflood** [comment] 2020-06-24 13:21
Closing this one because it's working for me, I can't reproduce any issue.

**Closed by xiaoxiaoflood** 2020-06-24 13:21 UTC
