### ISSUE TITLE
userChrome.js not loading at all, firefox 102.6 ESR

### ISSUE THREAD

**Issue by moejarrah** [xiaoxiaoflood/firefox-scripts#232] opened 2023-01-11 06:47 UTC
Script not loading at all firefox 102.6 ESR. Followed installation carefully. Any tips are welcome. thanks!

**Comment by krystian3w** [comment] 2023-01-11 12:28
You tested version older than: https://github.com/xiaoxiaoflood/firefox-scripts/tree/7ce14e8e423405fdb34abb516f0e6681f6a3408a?

**Comment by moejarrah** [comment] 2023-01-11 13:10
@krystian3w I tested the latest (Tested on Firefox Developer Edition 109.0b3) , should I try another version?

**Comment by krystian3w** [comment] 2023-01-11 13:24
IMO you should check version for 101 or 103 due author may don't add fallback (and ESR 115 is not published).

**Comment by moejarrah** [comment] 2023-01-11 13:37
Sorry I'm not aware of how to access older versions, could you guide me please? Thank you

**Comment by moejarrah** [comment] 2023-01-11 13:52
Never mind, I got it. Still not working though

**Comment by Lalarian** [comment] 2023-01-23 12:17
It's working for me in 109.0 I often had trouble installing the scripts, because all these Firefox directories are terribly confusing. What OS are you on, and can you write down the exact pathes where you placed which file nd folder?

**Comment by xiaoxiaoflood** [comment] 2023-02-23 03:59
Current userChromeJS (base files for installation) and two scripts are purposefully compatible with ESR because of Thunderbird that is based on ESR: *rebuild_userChrome.uc.js* and *StyloaiX*. If you find any bug related to these on current ESR or current Developer Edition, please open a new ticket. But I just did a quick test on v102 and it seems to be working fine.

Other scripts may or may not work, I don't keep backward compatibility to minimize maintenance complexity. You can always use older versions that should work.

I'll close this as unconfirmed. If you find an issue that I can reproduce step by step from a new profile, I'll try to fix it.

For general help, please use [Discussions](https://github.com/xiaoxiaoflood/firefox-scripts/discussions).

**Closed by xiaoxiaoflood** 2023-02-23 03:59 UTC
