### ISSUE TITLE
Greasemonkey

### ISSUE THREAD

**Issue by dezhavu** [xiaoxiaoflood/firefox-scripts#1] opened 2018-08-19 16:18 UTC
Hey mate, thanks for your great work, however with gresemonkey extension YouTube doesn't work (no video is being played):

1) neither directly at youtube:
https://www.youtube.com/watch?v=PmZjaYdS3fA&gl=US

Error: Could not establish connection. Receiving end does not exist. background.js:127:2
uncaught exception: g.Ld@https://www.youtube.com/yts/jsbin/player-vflbOM9Vw/en_US/base.js:216:25
 rI@https://www.youtube.com/yts/jsbin/player-vflbOM9Vw/en_US/base.js:2431:64
 NM@https://www.youtube.com/yts/jsbin/player-vflbOM9Vw/en_US/base.js:2717:119
 w_@https://www.youtube.com/yts/jsbin/player-vflbOM9Vw/en_US/base.js:4285:89
 @https://www.youtube.com/yts/jsbin/player-vflbOM9Vw/en_US/base.js:7687:161
 ytplayer.load@https://www.youtube.com/watch?v=PmZjaYdS3fA&gl=US:191:56537
 @https://www.youtube.com/watch?v=PmZjaYdS3fA&gl=US:191:56698
 @https://www.youtube.com/watch?v=PmZjaYdS3fA&gl=US:191:56630
Error: Permission denied to access object spf.js:39:25
TypeError: window.spf is undefined base.js:893:92
ReferenceError: spf is not defined watch:1453:1 

2) nor with embedded youtube videos:
http://forum.notebookreview.com/threads/what-song-are-you-listening-to-right-now-v4-0-no-autoplay-please.724641/page-631

Error: Could not establish connection. Receiving end does not exist. 	background.js:127:2
uncaught exception: g.Ld@https://www.youtube.com/yts/jsbin/player-vflbOM9Vw/en_US/base.js:216:25
 rI@https://www.youtube.com/yts/jsbin/player-vflbOM9Vw/en_US/base.js:2431:64
 NM@https://www.youtube.com/yts/jsbin/player-vflbOM9Vw/en_US/base.js:2717:119
 w_@https://www.youtube.com/yts/jsbin/player-vflbOM9Vw/en_US/base.js:4285:89
 @https://www.youtube.com/yts/jsbin/player-vflbOM9Vw/en_US/base.js:7687:161
 ytplayer.load@https://www.youtube.com/watch?v=PmZjaYdS3fA&gl=US:191:55815
 @https://www.youtube.com/watch?v=PmZjaYdS3fA&gl=US:191:55976
 @https://www.youtube.com/watch?v=PmZjaYdS3fA&gl=US:191:55908
Error: Permission denied to access object spf.js:39:25
 xb<	https://www.youtube.com/yts/jsbin/spf-vflhSOzLf/spf.js:39:25
 <anonymous>	https://www.youtube.com/yts/jsbin/spf-vflhSOzLf/spf.js:39:8
 <anonymous>	https://www.youtube.com/yts/jsbin/spf-vflhSOzLf/spf.js:1:2
TypeError: window.spf is undefined base.js:893:92
 uk.prototype.enable	https://www.youtube.com/yts/jsbin/www-en_US-vfl3Mzk7b/base.js:893:92
 g.Yh	https://www.youtube.com/yts/jsbin/www-en_US-vfl3Mzk7b/base.js:446:1
 <anonymous>	https://www.youtube.com/yts/jsbin/www-en_US-vfl3Mzk7b/base.js:902:1
 <anonymous>	https://www.youtube.com/yts/jsbin/www-en_US-vfl3Mzk7b/base.js:1:17
ReferenceError: spf is not defined watch:1453:1
<anonymous>	https://www.youtube.com/watch:1453:1

3) Same for Chrome Store, just doesnt load at all:

Error: Could not establish connection. Receiving end does not exist.
background.js:127:2
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: {
.... jinjaccalgkegednnccohejagnlnfdag:1
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: Da.... jinjaccalgkegednnccohejagnlnfdag:1
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: 
	.... jinjaccalgkegednnccohejagnlnfdag:1
TypeError: document.head is null inject.js:70:1
Error: Could not establish connection. Receiving end does not exist. background.js:127:2
Error: Could not establish connection. Receiving end does not exist.
background.js:127:2
CSI/start m=consumer:128:127
CSI/start m=consumer line 472 > eval:1:127
Error: Permission denied to access object
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: (f.... jinjaccalgkegednnccohejagnlnfdag:1
Error: Permission denied to access object

Any ideas how to get it working? I guess its breaking some CSP rules.. 
Legacy Greasemonkey is great for some special scripts tho

**Comment by xiaoxiaoflood** [comment] 2018-08-21 22:15
No problem here, Nightly 2018-08-20. Are you sure Greasemonkey is related to your issue? None of these logs references Greasemonkey code.

What UserJSs do you have enabled on these pages?

**Comment by dezhavu** [comment] 2018-08-23 12:35
Yep it was a script causing these troubles
https://greasyfork.org/en/scripts/19993-ru-adlist-js-fixes

Thanks, I had no idea what happened, will notify authors of the script.
Now everything works as its supposed to be. 

One thing is broken though - Addons Manager > Greasemonkey Scripts > Enable/Disable/Remove don't work anymore on FF62 (using beta 14), works with directly modifying config.xml or by hitting greasemonkey button on the site and unchecking.

TypeError: aAddon.enable is not a function[Learn More] extensions.js:1159:9
TypeError: aAddon.disable is not a function extensions.js:1177:9
TypeError: this.mAddon.disable is not a function extensions.xml:1311:13

**Comment by xiaoxiaoflood** [comment] 2018-08-23 22:35
The cause:
https://bugzilla.mozilla.org/show_bug.cgi?id=1461146

This should be fixed now, update your Greasemonkey. Thanks for reporting!

**Closed** 2018-08-26 07:38 UTC
